-- MySQL Script generated by MySQL Workbench
-- Fri 28 Jul 2017 10:56:45 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cea_trial_task
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cea_trial_task
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cea_trial_task` DEFAULT CHARACTER SET utf8 ;
USE `cea_trial_task` ;

-- -----------------------------------------------------
-- Table `cea_trial_task`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cea_trial_task`.`User` (
  `UserId` INT NOT NULL,
  `UserFirstName` VARCHAR(45) NULL,
  `UserLastName` VARCHAR(45) NULL,
  `PasswordHashed` VARCHAR(45) NULL,
  `IsActive` VARCHAR(45) NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cea_trial_task`.`UserIncome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cea_trial_task`.`UserIncome` (
  `UserIncomeId` INT NOT NULL,
  `UserId` INT NULL,
  `Income` DECIMAL(10,0) NULL,
  `IsCurrent` TINYINT(1) NULL,
  PRIMARY KEY (`UserIncomeId`),
  INDEX `fk_UserIncome_1_idx` (`UserId` ASC),
  CONSTRAINT `fk_UserIncome_1`
    FOREIGN KEY (`UserId`)
    REFERENCES `cea_trial_task`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cea_trial_task`.`UserPledge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cea_trial_task`.`UserPledge` (
  `UserPledgeId` INT NOT NULL,
  `UserId` INT NULL,
  `PledgeAmount` INT NULL,
  PRIMARY KEY (`UserPledgeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cea_trial_task`.`UserDonations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cea_trial_task`.`UserDonations` (
  `UserDonationId` INT NOT NULL,
  `Amount` INT NULL,
  `DonatedDate` DATE NULL,
  PRIMARY KEY (`UserDonationId`))
ENGINE = InnoDB;

CREATE USER 'cea_trial_user' IDENTIFIED BY 'Jalak8uWest!';

GRANT SELECT ON TABLE `cea_trial_task`.* TO 'cea_trial_user';
GRANT SELECT, INSERT, TRIGGER ON TABLE `cea_trial_task`.* TO 'cea_trial_user';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `cea_trial_task`.* TO 'cea_trial_user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
